name: build-webpack
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Debug variables
        run: |
          echo "github event: ${{ toJSON(github.event) }}"

      - name: Create build archive
        uses: actions/upload-artifact@v2
        with:
          name: webpack
          path: README.md
          retention-days: 2
