name: build-webpack
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Debug variables
        run: |
          echo "github object: ${{ toJSON(github) }}"

      - name: Create build archive
        uses: actions/upload-artifact@v2
        with:
          # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
          # for pull_requests, use HEAD of the proposed branch, for pushes to origin the current SHA
          name: "build-${{ github.event.pull_request.head.sha || github.sha }}"
          path: README.md
          retention-days: 2

      - name: Save github.event for follow-up workflows
        run: echo '${{ toJSON(github.event) }}' > /tmp/pr-event.json

      - name: Create artifact of event.json
        uses: actions/upload-artifact@v2
        with:
          name: pr-event.json
          path: /tmp/pr-event.json
