name: unit-tests
on:
  workflow_run:
    workflows: build-webpack
    types: [completed]

jobs:
  unit-tests:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        run: |
          echo "${{ toJSON(github) }}"
          echo "---------"
          echo "PR SHA to build: ${{ github.event.workflow_run.head_sha }}"

      - name: Download PR payload artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-webpack
          run_id: ${{ github.event.workflow_run.id }}
          name: pr-event.json

      - name: Show PR payload artifact
        run: |
          ls -lR
          cat pr-event.json
          rm pr-event.json

      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-webpack
          run_id: ${{ github.event.workflow_run.id }}

      - name: Show  all build artifacts
        run: ls -lR
